services:
  - type: web
    name: flask-backend
    runtime: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
    staticPublishPath: ./frontend/build